steps:
  - id: 'Pulling latest image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull europe-west9-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/build:latest || exit 0'
  - id: 'Building image'
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'europe-west9-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/build:$COMMIT_SHA'
      - '-t'
      - 'europe-west9-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/build:latest'
      - '--cache-from'
      - 'europe-west9-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/build:latest'
      - .
  - id: 'Pushing current image'
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west9-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/build:$COMMIT_SHA'
  - id: 'Pushing as latest image'
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west9-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/build:latest'
  - id: 'Deploying service'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - 'scripts/deploy-service.sh'
      - '$REPO_NAME'
images:
  - 'europe-west9-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/build:$COMMIT_SHA'
  - 'europe-west9-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/build:latest'
options:
  logging: CLOUD_LOGGING_ONLY
